# Generated by Django 5.1 on 2024-08-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_orderitem_product_orderitem_product_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address1',
            new_name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_address2',
        ),
    ]
