# Generated by Django 5.1 on 2024-08-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_shipping_address1_shippingaddress_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_email',
            new_name='shipping_phone',
        ),
    ]
