# Generated by Django 5.1 on 2024-08-29 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='img4',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, null=True, size=None),
        ),
    ]
