# Generated by Django 5.1 on 2024-09-02 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productvariant'),
        ),
    ]
