# Generated by Django 5.1 on 2024-09-03 05:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_product_image_1_product_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recently_viewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
